language: php
php:
- 5.5
- 5.6
- 7.0
- hhvm

install:
- sudo apt-get install gearman gearman-job-server libgearman-dev
- pecl channel-update pecl.php.net
- printf "\n" |  pecl install gearman-1.1.2
- travis_retry composer install --no-interaction --prefer-source

script:
- phpunit

matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm
  - php: 7.0

