language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm

before_install:
  - composer self-update

install:
- sudo apt-get install gearman gearman-job-server libgearman-dev php5-gearman
- travis_retry composer install --no-interaction --prefer-source

script:
- phpunit -c phpunit.xml

matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm
  - php: 7.0

